---
- name: nginx
  apt: pkg=nginx state=latest

- name: nginx | config
  template: src=../files/nginx/nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify: restart nginx

- name: nginx | disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: nginx | install app site
  template: src=../files/nginx/app.conf dest=/etc/nginx/sites-available/app.conf owner=root group=root mode=0644

- name: nginx | enable app site
  file: src=/etc/nginx/sites-available/app.conf dest=/etc/nginx/sites-enabled/app.conf state=link
  notify: restart nginx
