---
- name: php | extensions
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-fpm
    - php5-cli
    - php5-curl
    - php5-mysql

- name: php | fpm config
  template: src=../files/php/www.conf dest=/etc/php5/fpm/pool.d/www.conf owner=root group=root mode=0644
  notify: restart php

- name: php | php.ini config (fpm)
  copy: src=../files/php/php.ini dest=/etc/php5/fpm/php.ini owner=root group=root mode=0644
  notify: restart php

- name: php | php.ini config (cli)
  copy: src=../files/php/php.ini dest=/etc/php5/cli/php.ini owner=root group=root mode=0644
